language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script:  python TestSPMResultDataModel.py
# Update subtree nidm from main nidm repository
before_install: 
 - git config --global user.name "TravisCI"
 - git subtree pull --prefix nidm https://github.com/incf-nidash/nidm.git master --squash --no-edit